### ISSUE TITLE
The programming code is visible in the 2nd chapter

### ISSUE THREAD

**Issue by rrramble** [Mihonarium/hpmor-ru#45]
Some programming code (script) is visible in the [2nd chapter](https://xn--c1asakg.xn--p1ai/book/1/2) just after its title:

`#include "стандартный отказ от прав.h"`

<img width="1022" alt="screenshot-chapter-2--2024-10-25" src="https://github.com/user-attachments/assets/5cdf6fac-9056-414b-9c33-ae5afbc80d0d">

**Comment by Mihonarium** [comment]
Это часть книги.

**Comment by rrramble** [comment]
Got it, sorry.
